import { Dataset } from './types';

export const DEFAULT_DATASETS: Dataset[] = [
  {
    id: 'product-orders',
    name: 'Style Product Orders & Transactions',
    description: 'Style house transaction histories tracking exact order prices, payment modalities, and purchase dates.',
    columns: [
      { name: 'Order_Number', type: 'string' },
      { name: 'Product', type: 'string' },
      { name: 'Price', type: 'number' },
      { name: 'Date', type: 'string' },
      { name: 'Payment_Method', type: 'string' }
    ],
    rows: [
      { Order_Number: 'TT-1001', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-08-15', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1001', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-08-15', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1002', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-08-15', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1003', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-08-16', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1004', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-08-16', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1005', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-08-17', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1005', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-08-17', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1006', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-08-18', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1007', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-08-18', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1008', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-08-19', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1009', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-08-19', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1009', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-08-19', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1010', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-08-20', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1011', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-08-20', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1012', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-08-21', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1013', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-08-21', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1014', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-08-22', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1015', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-08-22', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1015', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-08-22', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1016', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-08-23', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1017', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-08-24', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1018', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-08-24', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1018', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-08-24', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1019', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-08-25', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1020', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-08-25', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1021', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-08-26', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1022', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-08-26', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1023', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-08-27', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1024', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-08-27', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1025', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-08-28', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1025', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-08-28', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1026', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-08-29', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1027', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-08-29', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1028', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-08-30', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1029', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-08-30', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1029', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-08-30', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1030', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-08-31', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1031', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-09-01', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1032', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-09-01', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1033', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-09-02', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1034', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-09-02', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1034', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-09-02', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1035', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-09-03', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1036', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-09-03', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1037', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-09-04', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1038', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-09-04', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1039', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-09-05', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1040', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-09-05', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1040', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-09-05', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1041', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-09-06', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1042', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-09-06', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1043', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-09-07', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1044', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-09-08', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1045', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-09-08', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1046', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-09-09', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1047', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-09-09', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1047', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-09-09', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1048', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-09-10', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1049', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-09-10', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1050', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-09-11', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1051', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-09-12', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1052', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-09-12', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1053', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-09-13', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1054', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-09-13', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1054', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-09-13', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1055', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-09-14', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1056', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-09-14', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1057', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-09-15', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1058', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-09-16', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1059', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-09-16', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1059', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-09-16', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1060', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-09-17', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1061', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-09-17', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1062', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-09-18', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1063', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-09-18', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1064', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-09-19', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1065', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-09-19', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1065', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-09-19', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1066', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-09-20', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1067', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-09-21', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1068', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-09-21', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1069', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-09-22', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1070', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-09-22', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1071', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-09-23', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1072', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-09-23', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1072', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-09-23', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1073', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-09-24', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1074', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-09-24', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1075', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-09-25', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1076', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-09-26', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1077', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-09-26', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1078', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-09-27', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1079', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-09-27', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1079', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-09-27', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1080', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-09-28', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1081', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-09-28', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1082', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-09-29', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1083', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-09-29', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1084', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-09-30', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1084', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-09-30', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1085', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-10-01', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1086', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-10-01', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1087', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-10-02', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1088', Product: 'Technical Performance Joggers', Price: 75, Date: '2025-10-02', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1089', Product: 'Multi-Pocket Cargo Shorts', Price: 58, Date: '2025-10-03', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1090', Product: 'Drawstring Linen Trousers', Price: 92, Date: '2025-10-03', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1091', Product: 'Classic Denim Overalls', Price: 115, Date: '2025-10-04', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1092', Product: 'Tailored Wool Dress Trousers', Price: 145, Date: '2025-10-04', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1092', Product: 'Classic Fit Chinos', Price: 78, Date: '2025-10-04', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1093', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-10-05', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1094', Product: 'Striped Seersucker Trousers', Price: 95, Date: '2025-10-05', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1095', Product: 'Relaxed Fit Corduroy Trousers', Price: 85, Date: '2025-10-06', Payment_Method: 'eWallet' },
      { Order_Number: 'TT-1096', Product: 'Premium Tailored Trousers', Price: 175, Date: '2025-10-06', Payment_Method: 'Cash' },
      { Order_Number: 'TT-1097', Product: 'Flannel-Lined Canvas Work Pants', Price: 98, Date: '2025-10-07', Payment_Method: 'Credit Card' },
      { Order_Number: 'TT-1097', Product: 'Slim-Fit Denim Jeans', Price: 88, Date: '2025-10-07', Payment_Method: 'Debit Card' },
      { Order_Number: 'TT-1098', Product: 'Double-Pleated Khaki Trousers', Price: 82, Date: '2025-10-07', Payment_Method: 'eWallet' }
    ]
  },
  {
    id: 'sales-marketing',
    name: 'Sales & Marketing Performance',
    description: 'Quarterly sales revenue, expenditures, profitability, and customer acquisition metrics segmented by regional categories.',
    columns: [
      { name: 'Month', type: 'string' },
      { name: 'Quarter', type: 'string' },
      { name: 'Region', type: 'string' },
      { name: 'Product_Category', type: 'string' },
      { name: 'Ad_Spend', type: 'number' },
      { name: 'Sales', type: 'number' },
      { name: 'Net_Profit', type: 'number' },
      { name: 'New_Customers', type: 'number' }
    ],
    rows: [
      { Month: 'January', Quarter: 'Q1', Region: 'North America', Product_Category: 'Electronics', Ad_Spend: 3200, Sales: 24500, Net_Profit: 8600, New_Customers: 410 },
      { Month: 'January', Quarter: 'Q1', Region: 'Europe', Product_Category: 'Electronics', Ad_Spend: 2100, Sales: 18200, Net_Profit: 5400, New_Customers: 290 },
      { Month: 'January', Quarter: 'Q1', Region: 'Asia Pacific', Product_Category: 'Electronics', Ad_Spend: 1500, Sales: 15400, Net_Profit: 4500, New_Customers: 210 },
      { Month: 'January', Quarter: 'Q1', Region: 'North America', Product_Category: 'Furniture', Ad_Spend: 1800, Sales: 12400, Net_Profit: 3100, New_Customers: 180 },
      { Month: 'January', Quarter: 'Q1', Region: 'Europe', Product_Category: 'Furniture', Ad_Spend: 1400, Sales: 10800, Net_Profit: 2500, New_Customers: 140 },
      { Month: 'February', Quarter: 'Q1', Region: 'North America', Product_Category: 'Electronics', Ad_Spend: 3500, Sales: 28900, Net_Profit: 10400, New_Customers: 480 },
      { Month: 'February', Quarter: 'Q1', Region: 'Europe', Product_Category: 'Electronics', Ad_Spend: 2400, Sales: 21400, Net_Profit: 7100, New_Customers: 340 },
      { Month: 'February', Quarter: 'Q1', Region: 'Asia Pacific', Product_Category: 'Electronics', Ad_Spend: 1800, Sales: 17200, Net_Profit: 5100, New_Customers: 260 },
      { Month: 'February', Quarter: 'Q1', Region: 'North America', Product_Category: 'Furniture', Ad_Spend: 1900, Sales: 13500, Net_Profit: 3500, New_Customers: 190 },
      { Month: 'February', Quarter: 'Q1', Region: 'Europe', Product_Category: 'Furniture', Ad_Spend: 1500, Sales: 11200, Net_Profit: 2800, New_Customers: 150 },
      { Month: 'March', Quarter: 'Q1', Region: 'North America', Product_Category: 'Electronics', Ad_Spend: 4200, Sales: 34200, Net_Profit: 12500, New_Customers: 590 },
      { Month: 'March', Quarter: 'Q1', Region: 'Europe', Product_Category: 'Electronics', Ad_Spend: 2800, Sales: 25600, Net_Profit: 8900, New_Customers: 410 },
      { Month: 'March', Quarter: 'Q1', Region: 'Asia Pacific', Product_Category: 'Electronics', Ad_Spend: 2200, Sales: 19900, Net_Profit: 6200, New_Customers: 310 },
      { Month: 'March', Quarter: 'Q1', Region: 'North America', Product_Category: 'Furniture', Ad_Spend: 2200, Sales: 15800, Net_Profit: 4200, New_Customers: 220 },
      { Month: 'March', Quarter: 'Q1', Region: 'Europe', Product_Category: 'Furniture', Ad_Spend: 1600, Sales: 12900, Net_Profit: 3200, New_Customers: 170 },
      { Month: 'April', Quarter: 'Q2', Region: 'North America', Product_Category: 'Electronics', Ad_Spend: 4000, Sales: 31500, Net_Profit: 11200, New_Customers: 520 },
      { Month: 'April', Quarter: 'Q2', Region: 'Europe', Product_Category: 'Electronics', Ad_Spend: 3100, Sales: 27100, Net_Profit: 9400, New_Customers: 440 },
      { Month: 'April', Quarter: 'Q2', Region: 'Asia Pacific', Product_Category: 'Electronics', Ad_Spend: 2500, Sales: 22500, Net_Profit: 7100, New_Customers: 350 },
      { Month: 'April', Quarter: 'Q2', Region: 'North America', Product_Category: 'Furniture', Ad_Spend: 2600, Sales: 18500, Net_Profit: 5100, New_Customers: 270 },
      { Month: 'April', Quarter: 'Q2', Region: 'Europe', Product_Category: 'Furniture', Ad_Spend: 1800, Sales: 14200, Net_Profit: 3600, New_Customers: 180 },
      { Month: 'May', Quarter: 'Q2', Region: 'North America', Product_Category: 'Electronics', Ad_Spend: 4600, Sales: 38900, Net_Profit: 14100, New_Customers: 640 },
      { Month: 'May', Quarter: 'Q2', Region: 'Europe', Product_Category: 'Electronics', Ad_Spend: 3500, Sales: 31200, Net_Profit: 10900, New_Customers: 490 },
      { Month: 'May', Quarter: 'Q2', Region: 'Asia Pacific', Product_Category: 'Electronics', Ad_Spend: 2700, Sales: 24800, Net_Profit: 7900, New_Customers: 380 },
      { Month: 'May', Quarter: 'Q2', Region: 'North America', Product_Category: 'Furniture', Ad_Spend: 2800, Sales: 20100, Net_Profit: 5500, New_Customers: 290 },
      { Month: 'May', Quarter: 'Q2', Region: 'Europe', Product_Category: 'Furniture', Ad_Spend: 1900, Sales: 15300, Net_Profit: 3900, New_Customers: 195 },
      { Month: 'June', Quarter: 'Q2', Region: 'North America', Product_Category: 'Electronics', Ad_Spend: 5500, Sales: 45200, Net_Profit: 16800, New_Customers: 750 },
      { Month: 'June', Quarter: 'Q2', Region: 'Europe', Product_Category: 'Electronics', Ad_Spend: 3900, Sales: 34900, Net_Profit: 12200, New_Customers: 540 },
      { Month: 'June', Quarter: 'Q2', Region: 'Asia Pacific', Product_Category: 'Electronics', Ad_Spend: 3100, Sales: 28200, Net_Profit: 9100, New_Customers: 420 },
      { Month: 'June', Quarter: 'Q2', Region: 'North America', Product_Category: 'Furniture', Ad_Spend: 3100, Sales: 23400, Net_Profit: 6400, New_Customers: 330 },
      { Month: 'June', Quarter: 'Q2', Region: 'Europe', Product_Category: 'Furniture', Ad_Spend: 2100, Sales: 17100, Net_Profit: 4400, New_Customers: 210 }
    ]
  },
  {
    id: 'fitness-tracker',
    name: 'Personal Fitness & Sleep Log',
    description: 'A 14-day record of personal activity, sleep dynamics, energy self-scores, and step goals indicating physiological progress.',
    columns: [
      { name: 'Day', type: 'string' },
      { name: 'Steps', type: 'number' },
      { name: 'Distance_KM', type: 'number' },
      { name: 'Active_Minutes', type: 'number' },
      { name: 'Calories_Burned', type: 'number' },
      { name: 'Sleep_Hours', type: 'number' },
      { name: 'Energy_Score', type: 'number' },
      { name: 'Hydration_ML', type: 'number' }
    ],
    rows: [
      { Day: 'Mon, Jun 01', Steps: 8400, Distance_KM: 5.8, Active_Minutes: 45, Calories_Burned: 2250, Sleep_Hours: 6.8, Energy_Score: 6, Hydration_ML: 1800 },
      { Day: 'Tue, Jun 02', Steps: 10200, Distance_KM: 7.2, Active_Minutes: 60, Calories_Burned: 2450, Sleep_Hours: 7.2, Energy_Score: 8, Hydration_ML: 2100 },
      { Day: 'Wed, Jun 03', Steps: 12500, Distance_KM: 8.9, Active_Minutes: 80, Calories_Burned: 2680, Sleep_Hours: 7.5, Energy_Score: 9, Hydration_ML: 2500 },
      { Day: 'Thu, Jun 04', Steps: 6100, Distance_KM: 4.2, Active_Minutes: 25, Calories_Burned: 1980, Sleep_Hours: 5.5, Energy_Score: 4, Hydration_ML: 1500 },
      { Day: 'Fri, Jun 05', Steps: 9800, Distance_KM: 6.9, Active_Minutes: 50, Calories_Burned: 2320, Sleep_Hours: 8.1, Energy_Score: 8, Hydration_ML: 2000 },
      { Day: 'Sat, Jun 06', Steps: 14100, Distance_KM: 10.1, Active_Minutes: 95, Calories_Burned: 2900, Sleep_Hours: 8.5, Energy_Score: 9, Hydration_ML: 2800 },
      { Day: 'Sun, Jun 07', Steps: 11000, Distance_KM: 7.8, Active_Minutes: 70, Calories_Burned: 2500, Sleep_Hours: 9.0, Energy_Score: 10, Hydration_ML: 2400 },
      { Day: 'Mon, Jun 08', Steps: 7900, Distance_KM: 5.5, Active_Minutes: 40, Calories_Burned: 2150, Sleep_Hours: 6.2, Energy_Score: 5, Hydration_ML: 1700 },
      { Day: 'Tue, Jun 09', Steps: 10500, Distance_KM: 7.4, Active_Minutes: 58, Calories_Burned: 2410, Sleep_Hours: 7.4, Energy_Score: 7, Hydration_ML: 2200 },
      { Day: 'Wed, Jun 10', Steps: 11400, Distance_KM: 8.1, Active_Minutes: 65, Calories_Burned: 2550, Sleep_Hours: 7.0, Energy_Score: 8, Hydration_ML: 2300 },
      { Day: 'Thu, Jun 11', Steps: 9000, Distance_KM: 6.3, Active_Minutes: 48, Calories_Burned: 2280, Sleep_Hours: 7.1, Energy_Score: 7, Hydration_ML: 1900 },
      { Day: 'Fri, Jun 12', Steps: 12200, Distance_KM: 8.6, Active_Minutes: 75, Calories_Burned: 2600, Sleep_Hours: 7.8, Energy_Score: 9, Hydration_ML: 2400 },
      { Day: 'Sat, Jun 13', Steps: 15300, Distance_KM: 11.2, Active_Minutes: 110, Calories_Burned: 3100, Sleep_Hours: 8.2, Energy_Score: 10, Hydration_ML: 3000 },
      { Day: 'Sun, Jun 14', Steps: 8500, Distance_KM: 6.0, Active_Minutes: 40, Calories_Burned: 2180, Sleep_Hours: 8.8, Energy_Score: 8, Hydration_ML: 2000 }
    ]
  },
  {
    id: 'saas-adoption',
    name: 'SaaS Client Adoption Profiles',
    description: 'Aggregated product metrics for customer organizations, categorizing plan tiers, company size, system utilization, ticket volume, and Net Promoter Score (NPS).',
    columns: [
      { name: 'Company_Name', type: 'string' },
      { name: 'Sector', type: 'string' },
      { name: 'Plan_Tier', type: 'string' },
      { name: 'Active_Users', type: 'number' },
      { name: 'System_Usage_Pct', type: 'number' },
      { name: 'Open_Tickets', type: 'number' },
      { name: 'NPS', type: 'number' },
      { name: 'Monthly_Spend', type: 'number' }
    ],
    rows: [
      { Company_Name: 'Acme Corp', Sector: 'Technology', Plan_Tier: 'Enterprise', Active_Users: 450, System_Usage_Pct: 84.5, Open_Tickets: 3, NPS: 9, Monthly_Spend: 4500 },
      { Company_Name: 'Apex Health', Sector: 'Healthcare', Plan_Tier: 'Enterprise', Active_Users: 380, System_Usage_Pct: 78.2, Open_Tickets: 5, NPS: 8, Monthly_Spend: 3900 },
      { Company_Name: 'Bright Media', Sector: 'Entertainment', Plan_Tier: 'Professional', Active_Users: 145, System_Usage_Pct: 62.0, Open_Tickets: 2, NPS: 7, Monthly_Spend: 1500 },
      { Company_Name: 'Delta Finance', Sector: 'Finance', Plan_Tier: 'Enterprise', Active_Users: 620, System_Usage_Pct: 91.1, Open_Tickets: 8, NPS: 10, Monthly_Spend: 6200 },
      { Company_Name: 'Ecolab Inc', Sector: 'Agriculture', Plan_Tier: 'Basic', Active_Users: 25, System_Usage_Pct: 41.5, Open_Tickets: 1, NPS: 6, Monthly_Spend: 350 },
      { Company_Name: 'Future Retail', Sector: 'Retail', Plan_Tier: 'Professional', Active_Users: 185, System_Usage_Pct: 70.8, Open_Tickets: 4, NPS: 8, Monthly_Spend: 1900 },
      { Company_Name: 'Genesis Labs', Sector: 'Healthcare', Plan_Tier: 'Professional', Active_Users: 160, System_Usage_Pct: 76.4, Open_Tickets: 3, NPS: 9, Monthly_Spend: 1700 },
      { Company_Name: 'Helix Logistics', Sector: 'Transportation', Plan_Tier: 'Professional', Active_Users: 210, System_Usage_Pct: 68.3, Open_Tickets: 6, NPS: 7, Monthly_Spend: 2100 },
      { Company_Name: 'Imperial Legal', Sector: 'Services', Plan_Tier: 'Basic', Active_Users: 40, System_Usage_Pct: 53.0, Open_Tickets: 0, NPS: 8, Monthly_Spend: 450 },
      { Company_Name: 'Jupiter Systems', Sector: 'Technology', Plan_Tier: 'Enterprise', Active_Users: 720, System_Usage_Pct: 95.6, Open_Tickets: 12, NPS: 9, Monthly_Spend: 7500 },
      { Company_Name: 'Keystone Edu', Sector: 'Education', Plan_Tier: 'Basic', Active_Users: 85, System_Usage_Pct: 35.2, Open_Tickets: 2, NPS: 5, Monthly_Spend: 600 },
      { Company_Name: 'Summit Energy', Sector: 'Energy', Plan_Tier: 'Enterprise', Active_Users: 290, System_Usage_Pct: 80.0, Open_Tickets: 4, NPS: 8, Monthly_Spend: 3100 },
      { Company_Name: 'Valour Pharma', Sector: 'Healthcare', Plan_Tier: 'Enterprise', Active_Users: 310, System_Usage_Pct: 83.1, Open_Tickets: 7, NPS: 7, Monthly_Spend: 3300 },
      { Company_Name: 'Zenith Retail', Sector: 'Retail', Plan_Tier: 'Professional', Active_Users: 130, System_Usage_Pct: 59.9, Open_Tickets: 1, NPS: 10, Monthly_Spend: 1400 }
    ]
  }
];
